### ISSUE TITLE
Edge creation key name invalid for sdk methods

### ISSUE THREAD

**Issue by jayrbolton** [kbase/index_runner_deluxe#100]
Seeing the following error. We need to slugify the method or module name in these edge ids:

```
edge from ws_workspace/483 to ws_object/483:13675 (import_obj.py:148)
1/17/2020 10:50:16 AM2020-01-17 18:50:16 INFO     Saving workspace vertex 483 (import_obj.py:159)
1/17/2020 10:50:16 AM2020-01-17 18:50:16 INFO     Saving ws_type_version, ws_type, and ws_type_module for KBaseSearch.SearchFeatureSet-1.1 (import_obj.py:221)
1/17/2020 10:50:16 AM2020-01-17 18:50:16 INFO     Saving ws_obj_created_with_method edge from ws_object_version/483:13675:1 to ws_method_version/KBase Search:UNKNOWN:UNKNOWN (import_obj.py:182)
1/17/2020 10:50:16 AM2020-01-17 18:50:16 ERROR    Error processing message: RuntimeError Error response from RE API: {
1/17/2020 10:50:16 AM  "created": 0,
1/17/2020 10:50:16 AM  "details": [
1/17/2020 10:50:16 AM    "at position 0: creating document failed with error 'edge attribute missing or invalid', offending document: {\"_from\":\"ws_object_version/483:13675:1\",\"_to\":\"ws_method_version/KBase Search:UNKNOWN:UNKNOWN\",\"method_params\":null,\"_key\":\"9e9c322383b220ec\",\"updated_at\":1579287016728}"
1/17/2020 10:50:16 AM  ],
1/17/2020 10:50:16 AM  "empty": 0,
1/17/2020 10:50:16 AM  "error": false,
1/17/2020 10:50:16 AM  "errors": 1,
1/17/2020 10:50:16 AM  "ignored": 0,
1/17/2020 10:50:16 AM  "updated": 0
1/17/2020 10:50:16 AM}
1/17/2020 10:50:16 AM (main.py:117)
1/17/2020 10:50:16 AM2020-01-17 18:50:16 ERROR    Traceback (most recent call last):
1/17/2020 10:50:16 AM  File "/app/src/index_runner/main.py", line 112, in main
1/17/2020 10:50:16 AM    _handle_msg(msg)
1/17/2020 10:50:16 AM  File "/app/src/index_runner/main.py", line 150, in _handle_msg
1/17/2020 10:50:16 AM    releng_importer.run_importer(obj, ws_info, msg)
1/17/2020 10:50:16 AM  File "/app/src/index_runner/releng_importer.py", line 18, in run_importer
1/17/2020 10:50:16 AM    import_object(obj, ws_info)
1/17/2020 10:50:16 AM  File "/app/src/index_runner/releng/import_obj.py", line 48, in import_object
1/17/2020 10:50:16 AM    _save_created_with_method_edge(obj_ver_key, obj.get('provenance'))
1/17/2020 10:50:16 AM  File "/app/src/index_runner/releng/import_obj.py", line 186, in _save_created_with_method_edge
1/17/2020 10:50:16 AM    'method_params': params
1/17/2020 10:50:16 AM  File "/app/src/utils/re_client.py", line 159, in save
1/17/2020 10:50:16 AM    raise RuntimeError(f'Error response from RE API: {resp.text}')
1/17/2020 10:50:16 AMRuntimeError: Error response from RE API: {
1/17/2020 10:50:16 AM  "created": 0,
1/17/2020 10:50:16 AM  "details": [
1/17/2020 10:50:16 AM    "at position 0: creating document failed with error 'edge attribute missing or invalid', offending document: {\"_from\":\"ws_object_version/483:13675:1\",\"_to\":\"ws_method_version/KBase Search:UNKNOWN:UNKNOWN\",\"method_params\":null,\"_key\":\"9e9c322383b220ec\",\"updated_at\":1579287016728}"
1/17/2020 10:50:16 AM  ],
1/17/2020 10:50:16 AM  "empty": 0,
1/17/2020 10:50:16 AM  "error": false,
1/17/2020 10:50:16 AM  "errors": 1,
1/17/2020 10:50:16 AM  "ignored": 0,
1/17/2020 10:50:16 AM  "updated": 0
1/17/2020 10:50:16 AM}
1/17/2020 10:50:16 AM
1/17/2020 10:50:16 AM (main.py:118)
1/17/2020 10:50:17 AM2020-01-17 18:50:17 DEBUG    obj_ref is 483/13676 (main.py:180)

```

**Comment by jayrbolton** [comment]
Fixed in #101
